server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:mem:basic-auth-db
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none # Disable Hibernate automatic schema creation. This will initialize the DB using schema.sql and data.sql

okta:
  oauth2:
    issuer: <your_okta_authorization_server_url> # e.g.: https://<your_okta_domain>/oauth2/<auth_server_id>