server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:mem:basic-auth-db
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none # Disable Hibernate automatic schema creation. This will initialize the DB using schema.sql and data.sql

okta:
  oauth2:
    issuer: https://dev-70519533.okta.com/oauth2/aus4mp1j9dkITiPAj5d7