CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(45) NOT NULL,
  password TEXT NOT NULL,
  algorithm VARCHAR(45) NOT NULL,
  role VARCHAR(45) NOT NULL,
  PRIMARY KEY (id));

CREATE TABLE authority (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  user INT NOT NULL,
  PRIMARY KEY (id));

CREATE TABLE product (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  price VARCHAR(45) NOT NULL,
  currency VARCHAR(45) NOT NULL,
  owner VARCHAR(45) NOT NULL,
  PRIMARY KEY (id));
