server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          okta: # client ID for the ClientRegistration
            client-id: <your_client_id>
            client-secret: <your_client_secret>

okta:
  oauth2:
    issuer: https://dev-70519533.okta.com/oauth2/aus4mp1j9dkITiPAj5d7
    client-id: <your_client_id>
    client-secret: <your_client_secret>
    scopes: openid, profile, email, READ, WRITE

products:
    uri: http://localhost:8090/getProducts