server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          okta: # client ID for the ClientRegistration
            client-id: <your_client_id>
            client-secret: <your_client_secret>

okta:
  oauth2:
    issuer: <your_okta_authorization_server_url> # e.g.: https://<your_okta_domain>/oauth2/<auth_server_id>    client-id: <your_client_id>
    client-secret: <your_client_secret>
    scopes: openid, profile, email, READ, WRITE

products:
    uri: http://localhost:8090/getProducts