server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:basic-auth-db
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none # Disable Hibernate automatic schema creation. This will initialize the DB using schema.sql and data.sql

  security:
    oauth2:
      resourceserver:
        opaque:
          introspection-uri: http://localhost:9000/oauth2/introspect
          introspection-client-id: suleyman
          introspection-client-secret: 1234