server:
  port: 8090
okta:
  oauth2:
    issuer: <your_okta_authorization_server_url> # example: https://<your_okta_domain>/oauth2/<auth_server_id>

spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: <okta_client_id>
            client-secret: <okta_client_secret>
        provider:
          okta:
            authorization-uri: https://<your_okta_domain>/oauth2/<auth_server_id>/v1/authorize
            token-uri: https://<your_okta_domain>/oauth2/<auth_server_id>/v1/token
            jwk-set-uri: https://<your_okta_domain>/oauth2/<auth_server_id>/v1/keys
  mongodb:
    embedded:
      version: 3.4.5
    # if you use embedded MongoDB, following configuration is not necessary.
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/product