server:
  port: 8090
okta:
  oauth2:
    issuer: <your_okta_authorization_server_url> # e.g.: https://<your_okta_domain>/oauth2/<auth_server_id>#

# if you use embedded MongoDB, this configuration is not necessary.
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product